services:

  auth:
    ports:
      - 8000:8000

  redis:
    ports:
      - "6379:6379"

  postgres:
    ports:
      - "5432:5432"

  jaeger:
    ports:
      - "6831:6831/udp"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - movies
    restart: unless-stopped

  tests:
    container_name: auth_tests
    image: auth
    environment:
      REDIS__HOST: redis
      POSTGRES__HOST: postgres
      JAEGER__HOST: jaeger
      POSTGRES__USER: ${POSTGRES__USER}
      POSTGRES__PASSWORD: ${POSTGRES__PASSWORD}
      POSTGRES__DB_NAME: ${POSTGRES__DB_NAME}
      APP__JWT_SECRET_KEY: ${APP__JWT_SECRET_KEY}
      SUPERUSER__USERNAME: ${SUPERUSER__USERNAME}
      SUPERUSER__PASSWORD: ${SUPERUSER__PASSWORD}
      DISABLE_TRACE: "True"
      DISABLE_LIMITER: "True"

    networks:
      - movies
    entrypoint: "bash -c 'flask db upgrade && python3 app_init.py && python3 -m unittest discover -s tests'"
    env_file:
      - .env
    depends_on:
      - redis
      - postgres